#!/usr/bin/python
# -*- coding: utf-8 -*-
import csv,sys
import matplotlib.pyplot as plt
font = {'family': 'Times New Roman', 'weight': 'normal', 'size': '14.0'}
plt.rc('font', **font)

# Color to plot
color='r'
# Figure resolution (when saving)
res=300

'''Utility to plot original csv-files containing traffic load traces
File should have only two columns with data, separated by commas:
	current_time,current_load
Other formats will cause errors.'''
if len(sys.argv)<2:
	print "Usage: csvplot filename.csv [-p]\n"
	sys.exit(0)

xl=[]
yl=[]
i=0
fname=sys.argv[1].split(".")
fname_part=".".join(fname[:-1])
print "Open file \"{}\", processing...".format(fname_part)
fd=open(sys.argv[1],'rU')
c=csv.reader(fd)
for row in c:
	i+=1
	if len(row)!=0:
		try:
			xl.append(float(row[0]))
			yl.append(float(row[1]))
		except ValueError:
			print "Inappropriate data detected in row {}: {}!".format(i,row)
	else:
		print "String {} is empty!".format(i)

# Check obtained arrays for length equality
if (len(xl)!=len(yl)):
	print "Wrong input data! X and Y arrays have different lengths"
	sys.exit(1)

# Plot
plt.plot(xl,yl,color)
plt.xlabel(u'Время, сек')
plt.ylabel(u'Интенсивность трафика, байт/сек')
plt.title(u"Интенсивность трафика (файл \"{}\")".format(fname_part)) 
plt.legend(loc='best')
plt.grid(True)
plt.savefig(fname_part+".png",format='png',dpi=res)
if (len(sys.argv)==3 and sys.argv[2]=='-p'):
	plt.show()
print "Ok!"